netcore-mvc/netcore-mvc/Controllers/SettingController.cs
using Common.DTO;
using Common.Exceptions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Services;
using System.Threading.Tasks;

namespace WebUI.Controllers
{
    public class SettingController : Controller
    {
        private readonly ISettingService _settingService;
        public SettingController(ISettingService settingService)
        {
            _settingService = settingService;
        }
        // GET: SettingController
        public async Task<ActionResult> Index()
        {
            return View(await _settingService.GetAll());
        }

        // GET: SettingController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SettingController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SettingController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(SettingDto setting)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var created = await _settingService.Add(setting);
                }
                catch(CustomException e)
                {
                    ModelState.AddModelError(e.HttpCode.ToString(), e.CustomMessage);
                    return View(setting);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(setting);
        }

        // GET: SettingController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                return View(await _settingService.Get(id));
            }
            catch (CustomException e)
            {
                ModelState.AddModelError(e.HttpCode.ToString(), e.CustomMessage);
                return View();
            }
        }

        // POST: SettingController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, SettingDto setting)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _settingService.Update(setting);
                }
                catch (CustomException e)
                {
                    ModelState.AddModelError(e.HttpCode.ToString(), e.CustomMessage);
                    return View();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(setting);
        }

        // GET: SettingController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                return View(await _settingService.Get(id));
            }
            catch (CustomException e)
            {
                ModelState.AddModelError(e.HttpCode.ToString(), e.CustomMessage);
                return View();
            }
        }

        // POST: SettingController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, SettingDto setting)
        {
            try
            {
                await _settingService.Delete(id);
            }
            catch (CustomException e)
            {
                ModelState.AddModelError(e.HttpCode.ToString(), e.CustomMessage);
                return View();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

netcore-mvc/netcore-mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC Template</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC Template</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Setting" asp-action="Index">Setting</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Secret">Secret Page</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year NTSprint
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>